[project]
name = "fp_factions"
prefix = "fp_factions"
author = "fparma"
template = "cba"
mainprefix = "z"
folder_optionals = false
sig_version = 3
version = "1.0.0"

exclude = [
    "*.psd",
    "*.png",
    "*.tga"
]
files = [
    "*.paa"
]

reuse_private_key = true
key_name = "fp_gear_v2"
authority = "fp_gear_v2"